### ISSUE TITLE
Is this open source?

### ISSUE THREAD

**Issue by krishnakanthpps** [OrdnanceSurvey/os-jmeter-aws#1]
Hi..

Is this open source and whats the license type.  I am working on something similar and would like to reuse some parts of your code.

**Comment by jskeates** [comment]
Yes, all the code is open under the Apache 2.0 license. You can check out [the `LICENSE` file](https://github.com/OrdnanceSurvey/os-jmeter-aws/blob/master/LICENSE) for more info. We'd love to see your work contributed back here! 😀
